### ISSUE TITLE
Unauthorized App Access

### ISSUE THREAD

**Issue by sehmusaydogdu** [vmware-samples/workspace-ONE-SDK-integration-samples#29]
### Describe the bug

I am trying use Android SDK 24.01.  I made framework level integration. 

To integrate at the Framework level, do the following tasks:
1. Add the Client SDK.
2. Add the Framework.
3. Initialize the Framework.

Even though I followed all the steps, I get the following error

Caused by: java.lang.RuntimeException: Unauthorized App Access. Add app to console and install via Anchor app. Error code: -71

### Reproduction steps

1.Even though I followed all the steps, I get the following error

Caused by: java.lang.RuntimeException: Unauthorized App Access. Add app to console and install via Anchor app. Error code: -71

### Expected behavior

I waited for the User Interface Screen Capture Images to appear.

https://vdc-download.vmware.com/vmwb-repository/dcr-public/35935117-d488-476d-80ee-35059e08902c/6d9256f5-662f-4359-8888-bc7549096dd9/WorkspaceONE_Android_BaseIntegration.pdf

**Comment by Maddy79** [comment]
@sehmusaydogdu  - The App has to be deployed via WS1 Intelligent Hub, the device needs to be enrolled to WS1 UEM console.

**Comment by sehmusaydogdu** [comment]
@Maddy79  - Actually, we did the same thing, but the error continues. Is there anything else to check?

**Comment by Maddy79** [comment]
How is the device enrolled, Legacy Android enrollment OR Android Enterprise ( PO / COPE etc)

**Comment by sehmusaydogdu** [comment]
We enrolled Android Enterprise

**Comment by Maddy79** [comment]
Is it possible to share the logcat logs ?

**Comment by sehmusaydogdu** [comment]
The log is as follows:


2024-02-29 13:27:06.228  4437-4437  AndroidRuntime          com.architecture.application             E  FATAL EXCEPTION: main
                                                                                                    Process: com.architecture.application, PID: 4437
                                                                                                    java.lang.ExceptionInInitializerError
                                                                                                    at com.airwatch.sdk.context.awsdkcontext.SDKDataModelImpl.isDeviceUDIDInitialized(Unknown Source:0)
                                                                                                    at com.airwatch.sdk.context.awsdkcontext.handlers.AWDeviceIDHandler.handle(Unknown Source:11)
                                                                                                    at com.airwatch.sdk.context.awsdkcontext.handlers.SDKBaseHandler.handleNextHandler(Unknown Source:76)
                                                                                                    at com.airwatch.keymanagement.unifiedpin.LoginPrecheckHandler.handle(Unknown Source:12)
                                                                                                    at com.airwatch.sdk.context.awsdkcontext.chain.SDKLoginSplashChain.process(Unknown Source:87)
                                                                                                    at com.airwatch.login.ui.activity.SDKSplashActivity.onResume(Unknown Source:28)
                                                                                                    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1603)
                                                                                                    at android.app.Activity.performResume(Activity.java:9119)
                                                                                                    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5399)
                                                                                                    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5507)
                                                                                                    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
                                                                                                    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
                                                                                                    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
                                                                                                    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
                                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
                                                                                                    at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    at android.os.Looper.loop(Looper.java:319)
                                                                                                    at android.app.ActivityThread.main(ActivityThread.java:8913)
                                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
                                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
                                                                                                    Caused by: java.lang.RuntimeException: Unauthorized App Access. Add app to console and install via Anchor app. Error code: -71
                                                                                                    at com.airwatch.util.NotificationUtility.notifyAppNotAccessible(Unknown Source:74)
                                                                                                    at com.airwatch.core.AirWatchDevice.loadNativeLibs(Unknown Source:61)
                                                                                                    at com.airwatch.core.AirWatchDevice.<clinit>(Unknown Source:76)
                                                                                                    at com.airwatch.sdk.context.awsdkcontext.SDKDataModelImpl.isDeviceUDIDInitialized(Unknown Source:0) 
                                                                                                    at com.airwatch.sdk.context.awsdkcontext.handlers.AWDeviceIDHandler.handle(Unknown Source:11) 
                                                                                                    at com.airwatch.sdk.context.awsdkcontext.handlers.SDKBaseHandler.handleNextHandler(Unknown Source:76) 
                                                                                                    at com.airwatch.keymanagement.unifiedpin.LoginPrecheckHandler.handle(Unknown Source:12) 
                                                                                                    at com.airwatch.sdk.context.awsdkcontext.chain.SDKLoginSplashChain.process(Unknown Source:87) 
                                                                                                    at com.airwatch.login.ui.activity.SDKSplashActivity.onResume(Unknown Source:28) 
                                                                                                    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1603) 
                                                                                                    at android.app.Activity.performResume(Activity.java:9119) 
                                                                                                    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5399) 
                                                                                                    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5507) 
                                                                                                    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57) 
                                                                                                    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
                                                                                                    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180) 
                                                                                                    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98) 
                                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685) 
                                                                                                    at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    at android.os.Looper.loopOnce(Looper.java:230) 
                                                                                                    at android.os.Looper.loop(Looper.java:319) 
                                                                                                    at android.app.ActivityThread.main(ActivityThread.java:8913) 
                                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608) 
                                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 
                                                                                                    Caused by: java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/app/~~etYPzlXMn-UZib2g8PAtxA==/com.architecture.application-ngHxlovgkWbOqaCkfVKYww==/base.apk!/lib/arm64-v8a/libcoredevice.so": -3
                                                                                                    at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
                                                                                                    at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
                                                                                                    at java.lang.System.loadLibrary(System.java:1661)
                                                                                                    at com.airwatch.core.AirWatchDevice.loadNativeLibs(Unknown Source:9)
                                                                                                    at com.airwatch.core.AirWatchDevice.<clinit>(Unknown Source:76) 
                                                                                                    at com.airwatch.sdk.context.awsdkcontext.SDKDataModelImpl.isDeviceUDIDInitialized(Unknown Source:0) 
                                                                                                    at com.airwatch.sdk.context.awsdkcontext.handlers.AWDeviceIDHandler.handle(Unknown Source:11) 
                                                                                                    at com.airwatch.sdk.context.awsdkcontext.handlers.SDKBaseHandler.handleNextHandler(Unknown Source:76) 
                                                                                                    at com.airwatch.keymanagement.unifiedpin.LoginPrecheckHandler.handle(Unknown Source:12) 
                                                                                                    at com.airwatch.sdk.context.awsdkcontext.chain.SDKLoginSplashChain.process(Unknown Source:87) 
                                                                                                    at com.airwatch.login.ui.activity.SDKSplashActivity.onResume(Unknown Source:28) 
                                                                                                    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1603) 
                                                                                                    at android.app.Activity.performResume(Activity.java:9119) 
                                                                                                    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5399) 
                                                                                                    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5507) 
                                                                                                    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57) 
                                                                                                    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
                                                                                                    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180) 
                                                                                                    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98) 
                                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685) 
                                                                                                    at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    at android.os.Looper.loopOnce(Looper.java:230) 
                                                                                                    at android.os.Looper.loop(Looper.java:319) 
                                                                                                    at android.app.ActivityThread.main(ActivityThread.java:8913) 
                                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608) 
                                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 
2024-02-29 13:27:06.236  4437-4514  DJINNI                  com.architecture.application             E  java.lang.NoClassDefFoundError: <clinit> failed for class com.airwatch.core.AirWatchDevice; see exception in other thread
                                                                                                    at com.airwatch.crypto.openssl.OpenSSLCryptUtil.updateOpenSslSeed(Unknown Source:54)
                                                                                                    at com.airwatch.crypto.openssl.OpenSSLCryptUtil.getInstance(Unknown Source:106)
                                                                                                    at com.airwatch.util.RandomGenerator.genRandomKey(Unknown Source:0)
                                                                                                    at com.airwatch.crypto.provider.AWSecureRandom.engineNextBytes(Unknown Source:8)
                                                                                                    at java.security.SecureRandom.nextBytes(SecureRandom.java:480)
                                                                                                    at java.math.BigInteger.randomBits(BigInteger.java:719)
                                                                                                    at java.math.BigInteger.<init>(BigInteger.java:692)
                                                                                                    at com.vmware.xsw.settings.providers.internal.MasterKeyFromRSA.getOrCreateMasterKey(MasterKeyFromRSA.kt:67)
                                                                                                    at com.vmware.xsw.settings.providers.internal.MasterKeyFromRSA.encryptSymmetricKey(MasterKeyFromRSA.kt:43)
                                                                                                    at com.vmware.xsw.settings.providers.internal.AndroidDefaultAESCipher.getKey(AndroidDefaultAESCipher.kt:48)
                                                                                                    at com.vmware.xsw.settings.providers.internal.AndroidDefaultAESCipher.build(Androi
2024-02-29 13:27:06.238  4437-4514  WS1_ASMLog              com.architecture.application             E  (Logger.cpp.88) java.lang.NoClassDefFoundError: <clinit> failed for class com.airwatch.core.AirWatchDevice; see exception in other thread
2024-02-29 13:27:06.240  4437-4514  WS1                     com.architecture.application             E  onSDKException: Report from secure preference. code = APP_STATUS_ENDPOINT

**Comment by Maddy79** [comment]
Thanks @sehmusaydogdu  - we will check and update.

**Comment by Maddy79** [comment]
@sehmusaydogdu  - as per the logs, the app did not get installed from the WS1 Hub App Catalog on the device, please confirm.

**Comment by sehmusaydogdu** [comment]
The following steps were followed.

1. apk file has been created.
2. Hub App Catalog added.
3. Then the application was downloaded from Hub Catalog.
4. The application received an error.
5. To examine the tablet logs, Android Studio was connected via USB (developer mode was turned on).
6. The error received was still the same.

**Comment by sehmusaydogdu** [comment]
@Maddy79 Do you have any observations or developments?

**Comment by Maddy79** [comment]
@sehmusaydogdu we are checking this.

**Comment by Maddy79** [comment]
@sehmusaydogdu  - since the device is AE enrolled, can you trying adding the apk to enterprise PlayStore from UEM and on the device go to enterprise Playstore and install the app

**Comment by Maddy79** [comment]
Thanks @sehmusaydogdu , please confirm on the PlayStore query also.

**Comment by sehmusaydogdu** [comment]
We do not use Google Play Store because our applications are internal apps.
For this, we upload the apk file to the vmware airwatch application catalog. (we do not use google play store)

**Comment by Maddy79** [comment]
@sehmusaydogdu , since the device is Android Enterprise enrolled, can you try uploading the app via Enterprise PlayStore from WS1 UEM?

**Comment by sehmusaydogdu** [comment]
Let's try it and share the result.

Is there a solution to this for a local environment?

**Comment by sehmusaydogdu** [comment]
We already uploaded via WS1 UEM to the enterprise store. The error received was still the same.

**Comment by Maddy79** [comment]
@sehmusaydogdu  , so you see the app in Enterprise PlayStore on the device..rt?

**Comment by sehmusaydogdu** [comment]
i try download private google play store and it does not work.
i try download hub App catalog added store and it does not work.

**Comment by Maddy79** [comment]
@sehmusaydogdu  - I will suggest to raise a SR ticket with our support team so that we can get in call with you and look into this.

**Comment by sehmusaydogdu** [comment]
@Maddy79 Do you have any comments about this error?

2024-03-14 15:23:05.000  8256-8312  DJINNI                  com.architecture.application             E  java.lang.ExceptionInInitializerError
                                                                                                    	at com.airwatch.crypto.openssl.OpenSSLCryptUtil.updateOpenSslSeed(Unknown Source:54)
                                                                                                    	at com.airwatch.crypto.openssl.OpenSSLCryptUtil.getInstance(Unknown Source:62)
                                                                                                    	at com.airwatch.util.RandomGenerator.genRandomKey(Unknown Source:0)
                                                                                                    	at com.airwatch.crypto.provider.AWSecureRandom.engineNextBytes(Unknown Source:8)
                                                                                                    	at java.security.SecureRandom.nextBytes(SecureRandom.java:480)
                                                                                                    	at java.math.BigInteger.randomBits(BigInteger.java:719)
                                                                                                    	at java.math.BigInteger.<init>(BigInteger.java:692)
                                                                                                    	at com.vmware.xsw.settings.providers.internal.MasterKeyFromRSA.getOrCreateMasterKey(MasterKeyFromRSA.kt:67)
                                                                                                    	at com.vmware.xsw.settings.providers.internal.MasterKeyFromRSA.encryptSymmetricKey(MasterKeyFromRSA.kt:43)
                                                                                                    	at com.vmware.xsw.settings.providers.internal.AndroidDefaultAESCipher.getKey(AndroidDefaultAESCipher.kt:48)
                                                                                                    	at com.vmware.xsw.settings.providers.internal.AndroidDefaultAESCipher.build(AndroidDefaultAESCipher.kt:32)
                                                                                                    	at com.vmware.xsw.settings.providers.internal.AndroidDefaul
2024-03-14 15:23:05.003  8256-8312  WS1_ASMLog              com.ykb.sparxapplication             E  (Logger.cpp.88) java.lang.ExceptionInInitializerError
2024-03-14 15:23:05.004  8256-8312  WS1                     com.ykb.sparxapplication             E  onSDKException: Report from secure preference. code = APP_STATUS_ENDPOINT

**Comment by Maddy79** [comment]
@sehmusaydogdu  - were you able to raise the SR ticket?

**Comment by sehmusaydogdu** [comment]
Our last point;

Full MDM mode setup is not working the application is crashing ( log: Unauthorized App Access. Add app to console and install via Anchor app.)
But hybrid(work manage) mode (with work profile) setup is working. Per APP VPN is opening a Tunnel and the application is working.

We opened VMware Technical Support ticket, return is expected

**Comment by Maddy79** [comment]
@sehmusaydogdu  - So as per above , same App when installed on an Work Managed device works fine, whereas it crashes when installed on an Fully Managed (DO mode).

**Comment by sehmusaydogdu** [comment]
If there is no action to be taken on your side, I can close the case.

**Comment by Maddy79** [comment]
@sehmusaydogdu  - can you please confirm my comments above, you can keep this open, until we get it via the SR internally.

**Comment by devSdkOmnissa** [comment]
Hi @sehmusaydogdu,
To answer your question com.airwatch.core.AirWatchDevice package is coming from AWFramework library of SDK.
As per above conversation, i believe the last status as mentioned was same App when installed on an Work Managed device works fine, whereas it crashes when installed on an Fully Managed (DO mode).
- Can you please update what is the issue right now ? Did DO mode enrolment worked for you before ?
- What version of SDK are you using? 
- How are you consuming the SDK? via maven or via libs/**.jarfile?
- Did this issue started appearing after some specific version consumption?
- How are downloading the app via Enterprise play store or HUB app catalog?
- Please share the full Logs.
